version: '3.8'

services:
  eureka-server:
    image: mimo009/ms_demo_cicd:eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - ms_demo_network

  gateway:
    image: mimo009/ms_demo_cicd:gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 8
      start_period: 60s
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - ms_demo_network

  microservice1:
    image: mimo009/ms_demo_cicd:microservice1
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 8
      start_period: 60s
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - ms_demo_network

  microservice2:
    image: mimo009/ms_demo_cicd:microservice2
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 8
      start_period: 60s
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - ms_demo_network

networks:
  ms_demo_network:
    driver: bridge