version: '3.8'

services:
  eureka-server:
    image: mimo009/ms_demo_cicd:eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_COM_EXAMPLE=DEBUG
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - ms_demo_network

  gateway:
    image: mimo009/ms_demo_cicd:gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED=true
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID=true
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD=DEBUG
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 8
      start_period: 60s
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - ms_demo_network

  microservice1:
    image: mimo009/ms_demo_cicd:microservice1
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_APPLICATION_NAME=microservice1
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_COM_EXAMPLE=DEBUG
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 8
      start_period: 60s
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - ms_demo_network

  microservice2:
    image: mimo009/ms_demo_cicd:microservice2
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_APPLICATION_NAME=microservice2
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_COM_EXAMPLE=DEBUG
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 8
      start_period: 60s
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - ms_demo_network

networks:
  ms_demo_network:
    driver: bridge